version: "3.0"
services:
  spring:
    container_name: spring
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      DB_ENDPOINT: ${DB_ENDPOINT}
      DB_NAME: ${DB_NAME}
      DB_ID: ${DB_ID}
      DB_PW: ${DB_PW}